use_frameworks!
platform :ios, '10.3'

target 'scswift_Tests' do
  pod 'scswift', :path => '../'
  
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.3'
        end
    end
end
  
  
end
